# Background / foreground
background #2E2226
foreground #BF9393

# Cursor
cursor #D9BABA
cursor_text_color #A86867

# Selection
selection_background #8C4A4A
selection_foreground #ebdbb2

# Black
color0 #181926
color8 #181926

# Red (erreurs)
color1 #ed8796
color9 #ed8796

# Green (succès)
color2 #a6da95
color10 #a6da95

# Yellow (warnings)
color3 #eed49f
color11 #eed49f

# Blue
color4 #8aadf4
color12 #8aadf4

# Magenta
color5 #c6a0f6
color13 #c6a0f6

# Cyan
color6 #8bd5ca
color14 #8bd5ca

# White
color7 #e6e9ef
color15 #e6e9ef

# Orange (optionnel)
orange #ef9f76
brorange #ef9f76