general {
    lock_cmd = pidof hyprlock || hyprlock

    before_sleep_cmd = pidof hyprlock || hyprlock
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'

    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}

# Lock après 5 minutes
listener {
    timeout = 300
    on-timeout = pidof hyprlock || hyprlock
}

# Éteint les écrans 30 secondes après le lock
listener {
    timeout = 330

    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

# Suspend après 15 minutes
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
